# -*- coding: utf-8 -*-
"""invoices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W8ZtsFQXl0TzeFdy-IH5UtoK_lCANJCU
"""

past_due = [i for i in invoices if i.age>30 and not i.is_paid]
for j in past_due:
  j.status = "PAST DUE"

for i in invoices:
  if i.age > 30 and not i.is_paid:
    i.status = "PAST DUE"